CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    icon VARCHAR(50),
    color VARCHAR(7),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_categories_code UNIQUE (code),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

INSERT INTO categories (code, name, active)
VALUES ('UNCATEGORIZED', 'Без категории', TRUE);

CREATE TABLE statements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR(30) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    account_number VARCHAR(34),
    source_file_hash VARCHAR(64) NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    period_from DATE NOT NULL,
    period_to DATE NOT NULL,
    CONSTRAINT uk_statements_source_file_hash UNIQUE (source_file_hash)
);

CREATE INDEX idx_statements_bank_period
    ON statements (bank_name, period_from, period_to);

CREATE TABLE merchants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    normalized_name VARCHAR(255) NOT NULL,
    category_id BIGINT,
    confidence NUMERIC(3, 2) NOT NULL,
    detection_source VARCHAR(20) NOT NULL,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    times_matched BIGINT NOT NULL DEFAULT 0,
    confirmed_count BIGINT NOT NULL DEFAULT 0,
    rejected_count BIGINT NOT NULL DEFAULT 0,
    last_verified_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_merchants_normalized_name UNIQUE (normalized_name),
    CONSTRAINT fk_merchants_category
        FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT chk_merchants_confidence
        CHECK (confidence >= 0.00 AND confidence <= 1.00),
    CONSTRAINT chk_merchants_times_matched
        CHECK (times_matched >= 0),
    CONSTRAINT chk_merchants_confirmed_count
        CHECK (confirmed_count >= 0),
    CONSTRAINT chk_merchants_rejected_count
        CHECK (rejected_count >= 0)
);

CREATE INDEX idx_merchants_category_id
    ON merchants (category_id);

CREATE TABLE merchant_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_name VARCHAR(255) NOT NULL,
    normalized_alias VARCHAR(255) NOT NULL,
    merchant_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_merchant_aliases_normalized_alias UNIQUE (normalized_alias),
    CONSTRAINT fk_merchant_aliases_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchants (id)
);

CREATE INDEX idx_merchant_aliases_merchant_id
    ON merchant_aliases (merchant_id);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    transaction_date DATE NOT NULL,
    source_transaction_fingerprint VARCHAR(64) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    merchant_id BIGINT,
    statement_id BIGINT NOT NULL,
    CONSTRAINT fk_transactions_merchant
        FOREIGN KEY (merchant_id) REFERENCES merchants (id),
    CONSTRAINT fk_transactions_statement
        FOREIGN KEY (statement_id) REFERENCES statements (id),
    CONSTRAINT uk_transactions_statement_fingerprint
        UNIQUE (statement_id, source_transaction_fingerprint)
);

CREATE INDEX idx_transactions_statement_date
    ON transactions (statement_id, transaction_date);

CREATE INDEX idx_transactions_merchant_id
    ON transactions (merchant_id);
